// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcfJok5QQCSmYfWqS-BDpwCSj-tlliPu8',
    appId: '1:187756842537:web:70c0bcd4519706c9779638',
    messagingSenderId: '187756842537',
    projectId: 'money-tracker-app-e7f37',
    authDomain: 'money-tracker-app-e7f37.firebaseapp.com',
    storageBucket: 'money-tracker-app-e7f37.firebasestorage.app',
    measurementId: 'G-62NKGZBKRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs5PsDSqbz9Y9BnaMJCSKQhvttAH0wQxg',
    appId: '1:187756842537:android:12d1b532591e64d5779638',
    messagingSenderId: '187756842537',
    projectId: 'money-tracker-app-e7f37',
    storageBucket: 'money-tracker-app-e7f37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn22A1y_w-dnBQiYGNwer_mLsb5Qq5EFs',
    appId: '1:187756842537:ios:02f61831148828be779638',
    messagingSenderId: '187756842537',
    projectId: 'money-tracker-app-e7f37',
    storageBucket: 'money-tracker-app-e7f37.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn22A1y_w-dnBQiYGNwer_mLsb5Qq5EFs',
    appId: '1:187756842537:ios:02f61831148828be779638',
    messagingSenderId: '187756842537',
    projectId: 'money-tracker-app-e7f37',
    storageBucket: 'money-tracker-app-e7f37.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcfJok5QQCSmYfWqS-BDpwCSj-tlliPu8',
    appId: '1:187756842537:web:cdac8d0a23876164779638',
    messagingSenderId: '187756842537',
    projectId: 'money-tracker-app-e7f37',
    authDomain: 'money-tracker-app-e7f37.firebaseapp.com',
    storageBucket: 'money-tracker-app-e7f37.firebasestorage.app',
    measurementId: 'G-GKEZ08LK96',
  );
}
